/*
	Student ID: 1155107857
	Name: ZHANG Jingze
*/

/* Query 1 */
Spool result1.lst
SELECT L.LID AS LID, L.LEAGUE_NAME AS LEAGUE_NAME, R.REGION_NAME AS REGION_NAME, L.YEAR AS YEAR 
FROM LEAGUES L, REGIONS R
WHERE  L.RID = R.RID AND (L.SEASON = 'Spring' OR L.SEASON = 'Summer')
ORDER BY L.LID ASC;
Spool off

/* Query 2 */
CREATE OR REPLACE VIEW TEAMS_MORE_THAN_ONCE AS (
	SELECT CHAMPION_TID 
	FROM LEAGUES
	WHERE YEAR >= 2015 AND SEASON = 'Autumn'
	GROUP BY CHAMPION_TID 
	HAVING COUNT(*) > 1
);

Spool result2.lst
SELECT T.TID, T.TEAM_NAME, T.AVERAGE_AGE
FROM TEAMS T, TEAMS_MORE_THAN_ONCE TM
WHERE T.TID = TM.CHAMPION_TID
ORDER BY T.TID ASC;
Spool off

/* Query 3 */
CREATE OR REPLACE VIEW SEASON_MAX AS (
	SELECT MAX(W_NUM) AS W_NUM, SEASON 
	FROM (
		SELECT CHAMPION_TID, COUNT(LID) AS W_NUM, SEASON 
		FROM LEAGUES GROUP BY CHAMPION_TID, SEASON
		)
	GROUP BY SEASON
);

Spool result3.lst
SELECT TID, TEAM_NAME, AVERAGE_AGE, SM.SEASON AS SEASON, SM.W_NUM AS W_NUM
FROM 
(SELECT * FROM
	(SELECT CHAMPION_TID, COUNT(LID) AS W_NUM, SEASON 
	 FROM LEAGUES GROUP BY CHAMPION_TID, SEASON
	) WL_NUM 
	INNER JOIN TEAMS T ON WL_NUM.CHAMPION_TID = T.TID
) WT 
INNER JOIN SEASON_MAX SM ON (SM.W_NUM = WT.W_NUM AND SM.SEASON = WT.SEASON)
ORDER BY TID ASC, SEASON ASC;
Spool off

DROP VIEW SEASON_MAX;

/* Query 4 */
Spool result4.lst
SELECT * FROM
(SELECT LS.SID AS SID, S.SPONSOR_NAME AS SPONSOR_NAME, LS.L_NUM AS L_NUM
FROM (SELECT SID, COUNT(LID) AS L_NUM
		FROM SUPPORT GROUP BY SID) LS, SPONSORS S
WHERE S.SID = LS.SID
ORDER BY LS.SID ASC)
WHERE ROWNUM <= 5;
Spool off

/* Query 5 */
CREATE OR REPLACE VIEW SUPPORT_LIDS AS (
	SELECT SU.LID AS LID
	FROM SUPPORT SU, SPONSORS SP
	WHERE SU.SID = SP.SID AND SP.MARKET_VALUE > 50
);

CREATE OR REPLACE VIEW TEAM_LIDS AS (
	SELECT L.LID AS LID
	FROM TEAMS T, LEAGUES L
	WHERE T.TID = L.CHAMPION_TID AND T.AVERAGE_AGE < 30
);

Spool result5.lst
SELECT LID, LEAGUE_NAME 
FROM LEAGUES
WHERE LID IN (SELECT LID FROM SUPPORT_LIDS) AND LID IN (SELECT LID FROM TEAM_LIDS) AND (SEASON = 'Summer' OR SEASON = 'Winter')
ORDER BY LID DESC;
Spool off

DROP VIEW SUPPORT_LIDS;
DROP VIEW TEAM_LIDS;

/* Query 6 */
CREATE OR REPLACE VIEW SPONSOR_LEAGUE_REGION AS (
	SELECT SP_SU.LID, SID, RID, SPONSORSHIP, MARKET_VALUE, FOOTBALL_RANKING
	FROM (SELECT SP.SID, SU.LID, SP.MARKET_VALUE, SU.SPONSORSHIP FROM SPONSORS SP INNER JOIN SUPPORT SU ON SP.SID = SU.SID) SP_SU
			INNER JOIN (SELECT L.LID, L.RID, R.FOOTBALL_RANKING FROM LEAGUES L INNER JOIN REGIONS R ON L.RID = R.RID) LR 
				ON SP_SU.LID = LR.LID
	WHERE SP_SU.MARKET_VALUE > 40 AND LR.FOOTBALL_RANKING < 10
);

CREATE OR REPLACE VIEW SPONSOR_TO_REGION AS (
	SELECT SID, RID, SUM(SPONSORSHIP) AS SC_SUM
	FROM SPONSOR_LEAGUE_REGION
	GROUP BY SID, RID
);

Spool result6.lst
SELECT STR.SID, MAX(STR.SC_SUM/(SQRT(SP.MARKET_VALUE)*LOG(2, SQRT(R.FOOTBALL_RANKING) + 1))) AS HOT
FROM SPONSOR_TO_REGION STR, SPONSORS SP, REGIONS R
WHERE STR.SID = SP.SID AND STR.RID = R.RID
GROUP BY STR.SID
ORDER BY STR.SID DESC;
Spool off

DROP VIEW SPONSOR_LEAGUE_REGION;
DROP VIEW SPONSOR_TO_REGION;


/* Query 7 */

CREATE OR REPLACE VIEW SPONSOR_LEAGUE_REGION AS (
	SELECT SP_SU.LID, SID, RID, SPONSORSHIP
	FROM (SELECT SP.SID, SU.LID, SP.MARKET_VALUE, SU.SPONSORSHIP FROM SPONSORS SP INNER JOIN SUPPORT SU ON SP.SID = SU.SID) SP_SU
			INNER JOIN (SELECT L.LID, L.RID, R.FOOTBALL_RANKING FROM LEAGUES L INNER JOIN REGIONS R ON L.RID = R.RID) LR 
				ON SP_SU.LID = LR.LID
);

CREATE OR REPLACE VIEW SPONSOR_TO_REGION AS (
	SELECT SID, RID, SUM(SPONSORSHIP) AS SC_SUM
	FROM SPONSOR_LEAGUE_REGION
	GROUP BY SID, RID
);


CREATE OR REPLACE VIEW RID_HOT4 AS (
	SELECT STR.RID, STR.SC_SUM/(SQRT(SP.MARKET_VALUE)*LOG(2, SQRT(R.FOOTBALL_RANKING) + 1)) AS HOT_4
	FROM SPONSOR_TO_REGION STR, SPONSORS SP, REGIONS R
	WHERE STR.SID = SP.SID AND STR.RID = R.RID AND STR.SID = 4
);

CREATE OR REPLACE VIEW RID_HOT5 AS (
	SELECT STR.RID, STR.SC_SUM/(SQRT(SP.MARKET_VALUE)*LOG(2, SQRT(R.FOOTBALL_RANKING) + 1)) AS HOT_5
	FROM SPONSOR_TO_REGION STR, SPONSORS SP, REGIONS R
	WHERE STR.SID = SP.SID AND STR.RID = R.RID AND STR.SID = 5
);

CREATE OR REPLACE VIEW RID_HOT6 AS (
	SELECT STR.RID, STR.SC_SUM/(SQRT(SP.MARKET_VALUE)*LOG(2, SQRT(R.FOOTBALL_RANKING) + 1)) AS HOT_6
	FROM SPONSOR_TO_REGION STR, SPONSORS SP, REGIONS R
	WHERE STR.SID = SP.SID AND STR.RID = R.RID AND STR.SID = 6
);

CREATE OR REPLACE VIEW RID_HOT7 AS (
	SELECT STR.RID, STR.SC_SUM/(SQRT(SP.MARKET_VALUE)*LOG(2, SQRT(R.FOOTBALL_RANKING) + 1)) AS HOT_7
	FROM SPONSOR_TO_REGION STR, SPONSORS SP, REGIONS R
	WHERE STR.SID = SP.SID AND STR.RID = R.RID AND STR.SID = 7
);

CREATE OR REPLACE VIEW RID_HOTS AS (
	SELECT RT.RID, RRH4.HOT_4, RRH5.HOT_5, RRH6.HOT_6, RRH7.HOT_7
	FROM REGIONS RT, 
		 (SELECT R.RID, RH4.HOT_4 FROM REGIONS R LEFT JOIN RID_HOT4 RH4 ON R.RID = RH4.RID) RRH4,
		 (SELECT R.RID, RH5.HOT_5 FROM REGIONS R LEFT JOIN RID_HOT5 RH5 ON R.RID = RH5.RID) RRH5,
		 (SELECT R.RID, RH6.HOT_6 FROM REGIONS R LEFT JOIN RID_HOT6 RH6 ON R.RID = RH6.RID) RRH6,
		 (SELECT R.RID, RH7.HOT_7 FROM REGIONS R LEFT JOIN RID_HOT7 RH7 ON R.RID = RH7.RID) RRH7
	WHERE RT.RID = RRH4.RID AND RT.RID = RRH5.RID AND RT.RID = RRH6.RID AND RT.RID = RRH7.RID
);

Spool result7.lst
SELECT RID,HOT_4, HOT_5, HOT_6, HOT_7, GREATEST(NVL(HOT_4,0),NVL(HOT_5,0),NVL(HOT_6,0),NVL(HOT_7,0)) AS HOT_HIGH
FROM RID_HOTS
ORDER BY RID DESC;
Spool off

DROP VIEW SPONSOR_LEAGUE_REGION;
DROP VIEW SPONSOR_TO_REGION;
DROP VIEW RID_HOT4;
DROP VIEW RID_HOT5;
DROP VIEW RID_HOT6;
DROP VIEW RID_HOT7;
DROP VIEW RID_HOTS;

/* Query 8 */
CREATE OR REPLACE VIEW TEAM_WINS AS (
	SELECT CHAMPION_TID, COUNT(LID) AS W_NUM
	FROM LEAGUES L
	GROUP BY CHAMPION_TID 
);

CREATE OR REPLACE VIEW MOST_COMPETETIVE_TEAMS AS (
	SELECT CHAMPION_TID
	FROM TEAM_WINS TMWS
	WHERE TMWS.W_NUM = (SELECT MAX(W_NUM) FROM TEAM_WINS)
);

CREATE OR REPLACE VIEW MCT_LEAGUES_SID AS (
	SELECT SU.SID, L.LID
	FROM SUPPORT SU, LEAGUES L, MOST_COMPETETIVE_TEAMS MCT
	WHERE SU.LID = L.LID AND L.CHAMPION_TID = MCT.CHAMPION_TID
);

Spool result8.lst
SELECT DISTINCT MLS.SID, SP.SPONSOR_NAME
FROM MCT_LEAGUES_SID MLS, SPONSORS SP 
WHERE MLS.SID = SP.SID
ORDER BY MLS.SID ASC;
Spool off

DROP VIEW TEAM_WINS;
DROP VIEW MOST_COMPETETIVE_TEAMS;
DROP VIEW MCT_LEAGUES_SID;


